title: FELTOR
description: Numerical methods for SOL blob and turbulence simulations
google_analytics: 
show_downloads: true
remote_theme: mmistakes/minimal-mistakes
url: https://feltor-dev.github.io/
plugins:
  - jekyll-mentions
include:
  - _pages
  - .htaccess
  - _includes
teaser: /images/3dpic.jpg    
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
github: [metadata]